### ISSUE TITLE
Tofu board NVME SSD boot

### ISSUE THREAD

**Issue by Johnnie390** [oratek-ch/tofu#2]
Does the Tofu board support NVME SSD booting?

Please also see https://www.raspberrypi.org/forums/viewtopic.php?f=98&t=313228&p=1873879&hilit=cm4#p1873879
and https://github.com/raspberrypi/rpi-eeprom/issues/341

Any information much appreciated.

Regards,

JC

**Comment by aessig** [comment]
Hi Johnnie,

We have not tested it yet, but it should work. Have you tried following [Jeff's blog](https://www.jeffgeerling.com/blog/2021/raspberry-pi-can-boot-nvme-ssds-now)? 

Best regards,

**Comment by Johnnie390** [comment]
Hello all,
the Tofu board does indeed support NVME SSD booting. Please close this issue.
Thank you all for the assistance.

J390
