### ISSUE TITLE
rpiboot for eeprom upgrade doesn't work

### ISSUE THREAD

**Issue by klslz** [oratek-ch/tofu#5]
Hi.

It is not clear to me how to use the TOFU board for upgrading and or configuring the CM4 eeprom.

When attaching Tofu-USB-C to my computer, rpiboot won't connect to the TOFU board.

Note:
I do still have a NVME SSD attached. The TOFU board still seems to boot from NVME SSD.
From what I understand that shouldn't happen if powered from USB-C and connected to a USB host.

What am I doing wrong here?

Please add a note to your description how to run the eeprom upgrade or config change, in case I missed it.

**Comment by zlangbert** [comment]
This was also confusing for me. What I eventually realized is you need to be holding the small [nRPIBOOT button](https://tofu.oratek.com/#/?id=pin-configurations) when you power it on. This will allow it to connect to a computer for flashing.

Hopefully that helps you @klslz or anyone else who stumbles across this.
